### ISSUE TITLE
Error building classpath. Library com.github.liquidz/build.edn has sha and tag that point to different commits

### ISSUE THREAD

**Issue by sunng87** [liquidz/build.edn#27]
I'm getting this error after copying code from README. It seems the correct sha is `b276908`. I assume the README is automatically updated so there might be a bug in recent versions about replacing previous version.

**Comment by liquidz** [comment]
@sunng87 Thanks for your reporting!
There is an problem with the order of operations in the GitHub Actions workflow.
https://github.com/liquidz/build.edn/blob/2c69fd69f2d768541435bef111ccaad13011d6bf/.github/workflows/release.yml#L34

I'll fix this problem or change the README to use `:mvn/version` since build.edn has become deployable to clojars from v0.9.203 :)

**Comment by liquidz** [comment]
@sunng87 I've fixed in v0.9.216 :)

**Comment by sunng87** [comment]
Thank you for quick fix! 

Actually I don't quite understand why clojure tools.deps requires both tag and sha for dependency. It makes adding git dependencies painful.

By the way you may want to add my project [diehard](https://github.com/sunng87/diehard) to *projects using build.edn*

**Comment by liquidz** [comment]
@sunng87 
> By the way you may want to add my project [diehard](https://github.com/sunng87/diehard) to projects using build.edn

Wow. Thanks!
https://github.com/liquidz/build.edn/blob/main/README.adoc#projects-using-buildedn
