### ISSUE TITLE
[readme] Clojure CLI tools install not used

### ISSUE THREAD

**Issue by practicalli-johnny** [liquidz/build.edn#5]
The readme instructions for Clojure CLI show installing the tool using a :build alias.  However the deploy command also uses the :build alias, `-T:build` rather than calling the installed tool, `-Tbuild`

Is the deploy command incorrect, or does the tool not need to be installed (I assume the former)

Thank you

**Comment by liquidz** [comment]
@practicalli-john It seems that you are mistaken because the README example is bad.
build.edn does not require installing as a tool.
`clojure -T:build install` is same for `lein install`, so this is not a instruction for installing as a tool.
In the same way, `clojure -T:build deploy` is same for `lein deploy`.

So the `-T:build` is correct. (BTW `$ clojur -T:build deploy` in README is a typo 😇 )

**Comment by practicalli-johnny** [comment]
Ah, yes I see the confusion.  In many Clojure CLI `-T` execution approaches, there would be an install command followed by a command to use the tool.  My brain incorrectly selected that pattern

So the install in this case is an argument(?) to build.edn tool to install the jar built from the current project to the local Maven repository

As the :build alias does not define an :exec-fn, should the Clojure commands be called with -T (perhaps -T calls a function from the underlying tools.build library).
So much still to learn with tools.build.
